const map = new Map([
	['patent', [
        // { type: 'text',         id: 'serial',                        name: '案号'},
        // { type: 'text',         id: 'agency_serial',                  name: '事务所案号'},
        // { type: 'text',         id: 'english_title',                  name: '英文名称'},
        // { type: 'text',         id: 'proposal_title',                  name: '提案标题'},
        // { type: 'text',         id: 'start_year',                    name: '首次年费年度'},
        { type: 'select',       id: 'applicants',                    name: '申请人', url: '/api/applicants', data_key: 'applicants', placeholder: '过滤申请人'},
        // { type: 'text',         id: 'apn',                           name: '申请号'},
        // { type: 'date',          id: 'apd',                           name: '申请日',},
        // { type: 'date',          id: 'entrusting_time',               name: '委案时间'},
        // { type: 'select',       id: 'type',                          name: '专利类型',},
        // { type: 'select',        id: 'area',                           name: '申请地区',},
        // { type: 'select',        id: 'technical_field',                name: '技术领域',},
        // { type: 'text',         id: 'title',                          name: '标题'},
        // { type: 'date',          id: 'create_time',                    name: '立案时间'},
        // { type: 'text',         id: 'abstract',                       name: '摘要'},
        // { type: 'date',          id: 'public_date',                    name: '公开日'},
        // { type: 'text',         id: 'public_number',                  name: '公开号'}, 
        // { type: 'text',         id: 'proposal_serial',                name: '提案号'},
        // { type: 'select',       id: 'progress',                       name: '详细状态',},
        // { type: 'select',        id: 'flownode',                       name: '详细状态',},
        // { type: 'select',        id: 'legal_status',                   name: '法律状态',},
        { type: 'select',        id: 'inventors',                      name: '发明人',url: '/api/inventors', data_key: 'data', placeholder: '过滤发明人'},
        // { type: 'select',        id: 'alias_inventors',                name: '送件发明人',},
        // { type: 'select',        id: 'tags',                           name: '标签',},
        // { type: 'select',        id: 'branch',                         name: '部门',},
        // { type: 'select',        id: 'classification',                 name: '技术分类',},
        // { type: 'select',        id: 'products',                       name: '产品',},
        // { type: 'select',        id: 'product_relevance',              name: '产品相关',},
        // { type: 'select',        id: 'level',                          name: '案件等级',},
        // { type: 'select',        id: 'agency_type',                    name: '案件类型',},
        // { type: 'select',        id: 'ipr',                            name: '负责IPR',},
        // { type: 'select',        id: 'proposer',                       name: '技术联系人',},
        // { type: 'text',         id: 'priorities',                     name: '优先权'},
        // { type: 'text',         id: 'das',                            name: 'DAS码'},
        // { type: 'text',         id: 'tech_rank',                      name: '技术理解评分'},
        // { type: 'text',         id: 'draft_rank',                     name: '撰写质量评分'},
        // { type: 'text',         id: 'service_rank',                   name: '服务态度评分'},
        // { type: 'text',         id: 'negative_flag',                  name: '特别评价'},
        // { type: 'text',         id: 'negative_comment',               name: '评价详情'},
        // { type: 'select',        id: 'is_support',                     name: '是否已申请资助',}, //是否已申请资助
        // { type: 'select',        id: 'agency',                         name: '代理机构',}, //代理机构
        { type: 'select',        id: 'agent',                          name: '代理人', url: '/api/agents',data_key: 'members'}, //代理人
        // { type: 'date',          id: 'pre_exam_ok_date',               name: '初审合格日'},
        // { type: 'date',          id: 'sub_exam_start_date',            name: '进入实审日'},
        // { type: 'date',          id: 'sub_exam_start_date',            name: '进入实审日'},
        // { type: 'date',          id: 'issue_date',                       name: '公告日'},
        // { type: 'text',         id: 'issue_number',                     name: '公告号'},
        // { type: 'text',         id: 'main_ipc',                         name: '主国际分类号'},
        // { type: 'text',         id: 'ipr_review_times',                 name: 'IPR审核次数'},
        // { type: 'date',          id: 'pct_apd',                          name: '国际申请日'},
        // { type: 'date',          id: 'pct_19_expire_date',               name: 'PCT19条修改期限'},
        // { type: 'date',          id: 'pct_national_stage_expire_date',   name: 'PCT进入国家阶段期限'},
        // { type: 'date',          id: 'pct_pre_exam_expire_date',         name: 'PCT国际初步审查期限'},
        // { type: 'date',          id: 'pct_search_date',                  name: '国际检索日期'},
        // { type: 'date',          id: 'priority_expire_date',             name: '优先权届满期限'},
        // { type: 'text',         id: 'pct_no',                           name: '国际申请号'},
        // { type: 'date',         id: 'pct_priority_date',                name: '国际优先权日'},
        // { type: 'date',         id: 'pct_public_date',                  name: '国际公开日'},
        // { type: 'select',       id: 'pct_public_language',              name: '国际公开语言',},
        // { type: 'text',         id: 'pct_public_no',                    name: '国际公开号'},
        // { type: 'text',         id: 'board_number',                     name: '复审委内编号'},
        // { type: 'text',         id: 'agent_amending_period',            name: '代理人修改时间'},
        // { type: 'select',       id: 'is_biological',                  name: '是否与生物相关',},
        // { type: 'select',       id: 'is_division',                    name: '是否是分案申请',},
        // { type: 'select',       id: 'is_exam_request',                name: '是否提出实质审查请求',},
        // { type: 'select',       id: 'is_genetic',                     name: '是否依赖于遗传资源',},
        // { type: 'select',       id: 'is_leakage',                     name: '是否不丧失新颖性公开',},
        // { type: 'select',       id: 'is_pre_public',                  name: '是否提前公开',},
        // { type: 'select',       id: 'is_priority',                    name: '是否要求优先权',},
        // { type: 'select',       id: 'is_secure_check',                name: '是否保密审查',},
        // { type: 'select',       id: 'is_sequence',                    name: '是否有序列表',},
        // { type: 'select',       id: 'is_utility',                     name: '是否同实用新型/发明',},
        // { type: 'date',          id: 'ipr_final_edition_time',         name: 'IPR定稿时间'}, //IPR定稿时间
        // { type: 'date',          id: 'active_supplement_expire_date',  name: '主动修改期限'}, 
        // { type: 'text',         id: 'final_ipr_rank',                 name: 'IPR定稿评分'},//IPR定稿评分
        // { type: 'text',         id: 'group_number',                   name: '群组号码'},//群组号码
        // { type: 'text',         id: 'family_number',                  name: '专利族号码'},//专利族号码
        // { type: 'text',         id: 'project_name',                   name: '项目名称'},//研发项目名称
        // { type: 'text',         id: 'project_serial',                 name: '项目编号'},//研发项目编号
        // { type: 'text',         id: 'remark',                         name: '备注'},
        // { type: 'select',       id: 'awards',                         name: '专利奖',},
        // { type: 'select',       id: 'abbr',                           name: '部门简称',},
    ]],
]);
export {map};